### ISSUE TITLE
IRC servers with passwords

### ISSUE THREAD

**Issue by austinheap** [tb0hdan/torpedo#12]
I know IRC support is a work-in-progress but just wanted to request support for using IRC servers that require passwords. Great project btw!

**Comment by tb0hdan** [comment]
Should support password protected servers (works with registered nicks). Credentials are as follows:

`irc.freenode.net:7000:1` for SSL enabled host (w/o custom nick and password)
`somenick@irc.freenode.net:7000:1` for SSL enabled host + custom nick (w/o password)
`somenick@irc.freenode.net:7000:1:s0m3p4ssw0rd` for SSL enabled host + custom nick + password


launching bot (example with credentials above):

`torpedobot -ircapikey somenick@irc.freenode.net:7000:1:s0m3p4ssw0rd`

Please drop me a line if that worked so I can close this and #11 

Thanks.

**Comment by austinheap** [comment]
Wow @tb0hdan -- that's great! I'll test it now and report back.

**Comment by austinheap** [comment]
Works great, thanks again for the fast turn around!
